### ISSUE TITLE
AttributeError: 'module' object has no attribute '_linear'

### ISSUE THREAD

**Issue by nongbaoting** [nh2tran/DeepNovo#6]
I was try to run DeepNovo, but encouter the error,below.  By the way can I run DeepNovo-DIA with DDA MS data?
```
python ../deepnovo_main.py --train_dir train.example --decode --beam_search --beam_size 5
vocab_reverse  ['_PAD', '_GO', '_EOS', 'A', 'R', 'N', 'Nmod', 'D', 'Cmod', 'E', 'Q', 'Qmod', 'G', 'H', 'I', 'L', 'K', 'M', 'Mmod', 'F', 'P', 'S', 'T', 'W', 'Y', 'V']
vocab  {'_GO': 1, '_EOS': 2, '_PAD': 0, 'Mmod': 18, 'A': 3, 'E': 9, 'D': 7, 'G': 12, 'F': 19, 'I': 14, 'H': 13, 'K': 16, 'M': 17, 'L': 15, 'Nmod': 6, 'N': 5, 'Q': 10, 'P': 20, 'S': 21, 'R': 4, 'T': 22, 'W': 23, 'V': 25, 'Y': 24, 'Cmod': 8, 'Qmod': 11}
vocab_size  26
SPECTRUM_RESOLUTION  10
WINDOW_SIZE  10
MAX_LEN  50
_buckets  [12, 22, 32]
num_ion  8
l2_loss_weight  0.0
embedding_size  512
num_layers  1
num_units  512
keep_conv  0.75
keep_dense  0.5
batch_size  128
epoch_stop  20
train_stack_size  4500
valid_stack_size  15000
test_stack_size  4000
buffer_size  4000
steps_per_checkpoint  100
random_test_batches  10
max_gradient_norm  5.0
main()
2019-04-03 21:05:18.040118: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
DECODING MODEL
================================================================================
ModelInference: __init__()
================================================================================
ModelNetwork: __init__()
================================================================================
ModelInference: build_model()
================================================================================
ModelNetwork: build_network()
================================================================================
ModelNetwork: _build_cnn_spectrum()
WARNING:tensorflow:From /public/home/nong/bin/DeepNovo/deepnovo_model.py:473: __init__ (from tensorflow.python.ops.init_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.initializers.variance_scaling instead with distribution=uniform to get equivalent behavior.
================================================================================
ModelNetwork: _build_embedding_AAid()
================================================================================
ModelNetwork: _build_cnn_ion()
Traceback (most recent call last):
  File "../deepnovo_main.py", line 83, in <module>
    tf.app.run()
  File "/public/home/nong/miniconda3/envs/deepnovo/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "../deepnovo_main.py", line 35, in main
    deepnovo_main_modules.decode()
  File "/public/home/nong/bin/DeepNovo/deepnovo_main_modules.py", line 1982, in decode
    model.build_model()
  File "/public/home/nong/bin/DeepNovo/deepnovo_model.py", line 707, in build_model
    self.dropout_keep)
  File "/public/home/nong/bin/DeepNovo/deepnovo_model.py", line 310, in build_network
    direction)
  File "/public/home/nong/bin/DeepNovo/deepnovo_model.py", line 440, in _build_cnn_ion
    cnn_ion_logit = rnn_cell_impl._linear(args=cnn_ion_feature,
AttributeError: 'module' object has no attribute '_linear'
```

**Comment by nh2tran** [comment]
Hi,

The error seems to be caused by TensorFlow version. The code was tested with TensorFlow 1.2. In later versions, they may have moved/changed rnn_cell related codes. You may try to install TensorFlow 1.2, or you can try to modify the code, for example:
```
    linear_weight = tf.get_variable(
        name="linear_weight",
        shape=[self.num_units + self.vocab_size, self.vocab_size])
    linear_bias = tf.get_variable(
        name="linear_bias",
        shape=[self.vocab_size],
        initializer=tf.constant_initializer(0.1))
    cnn_ion_logit = tf.matmul(cnn_ion_feature, linear_weight) + linear_bias
```
